### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'torch_directml'

### ISSUE THREAD

**Issue by GryArt** [lshqqytiger/stable-diffusion-webui-directml#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm super new to all these and I have very basic knowledge on coding/python/running commands on Windows etc.

I'm trying to install SD first time but I'm running across this issue repeatedly. 
![Screenshot 2023-05-07 153604](https://user-images.githubusercontent.com/131767260/236664783-77ed4972-09bf-499f-9c2b-60941d7e251f.png)

### Steps to reproduce the problem

1. Go to Stable Diffusion
2. Run Webui_user.bath
3. ...

### What should have happened?

I followed normal steps and everything seems in place but can't get past these error

### Commit where the problem happens

nothing

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
No
```

### List of extensions

no

### Console logs

```Shell
No
```

**Comment by lshqqytiger** [comment]
Do you have a NVIDIA GPU driver installed?

**Comment by GryArt** [comment]
> Do you have a NVIDIA GPU driver installed?

That's the thing. I am AMD user, I have rx6700 10Gb. I guess everything is way simpler if I had Nvidia gpu?

**Comment by lshqqytiger** [comment]
Strange. torch-directml should be installed if you don't have `nvidia-smi` and `rocminfo`.
Do you get error message when you typed `nvidia-smi` and `rocminfo` in cmd or powershell?

**Comment by GryArt** [comment]
> Strange. torch-directml should be installed if you don't have `nvidia-smi` and `rocminfo`. Do you get error message when you typed `nvidia-smi` and `rocminfo` in cmd or powershell?

Where should I open cmd/powershell ?

**Comment by lshqqytiger** [comment]
Wherever. It will be better to clone repository instead of downloading .zip archive.
Clone this repository with `git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml.git` and try again.

**Comment by GryArt** [comment]
![image_2023-05-07_180917931](https://user-images.githubusercontent.com/131767260/236671252-0994f8fe-1fea-4d9a-94f9-644d66d23795.png)
It didn't take much to do that but after it's done, sadly, the problem persists.

**Comment by lshqqytiger** [comment]
Okay. Manually install torch-directml.
```
...> .\venv\Scripts\activate.ps1 (.bat if you are using cmd)
(venv) ...> pip install torch-directml
```
The problem should be solved.

**Comment by lshqqytiger** [comment]
Remove `stable-diffusion-webui-directml-master` folder and clone this repository into `SD AI` folder.

**Comment by GryArt** [comment]
> Okay. Manually install torch-directml.
> 
> ```
> ...> .\venv\Scripts\activate.ps1 (.bat if you are using cmd)
> (venv) ...> pip install torch-directml
> ```
> 
> The problem should be solved.

When I do that it says these, 
![Screenshot 2023-05-07 191018](https://user-images.githubusercontent.com/131767260/236674137-d4a6f520-9ea6-45a5-8ad8-97f3976b964e.png)

> Remove `stable-diffusion-webui-directml-master` folder and clone this repository into `SD AI` folder. Then run webui-user.bat in `stable-diffusion-webui-directml` folder.

And what do you mean by 'remove' ? The latter folder is inside the first one, what should I do with stable-diffusion-webui-directml

I moved/clone..? the repository to SD AI folder, deleted ....master folder, then run webui-user.bat in said folder. And now I'm seeing this error. 
![Screenshot 2023-05-07 191851](https://user-images.githubusercontent.com/131767260/236674456-60dfd382-096d-43e9-944a-5e43db306c0c.png)
Do you think its a progress?

**Comment by lshqqytiger** [comment]
It is trying to install torch built with CUDA.
That means it detected NVIDIA GPU driver on your PC.

**Comment by GryArt** [comment]
> It is trying to install torch built with CUDA. That means it detected NVIDIA GPU driver on your PC.

I managed to fix the issue yesterday by manually removing every last Nvidia driver files left, following your guide, then following this guide provided by 'If I was a kid' 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4299#issuecomment-1518725100

Even then, nothing happened, So I had to change 'false' >>> 'true' and then when I run webui.bat, it started downloading the latest model. 

BUT, Now I'm left with a few questions:

1. Since I deleted 'master' folder, and running webui.bat from `stable-diffusion-webui-directml folder, Where should I put other models I've manually downloaded? _Exm. OpenJourney v1.5_
2. I've tried yesterday a few txt2imag and img2img SD Upscale, but upscaling just not working. I mean it's running, but when I download the output image and see it, the upscaled img is even worse quality that the OG. How do I know what I did was right and SD is now running without any issue?

Thanks for your time btw.

`

**Comment by SgtEpsilon** [comment]
I have the same issue except there's no nvidia drivers on my PC and followed all the same instructions in this thread but nothing seems to be fixing the issue.
GPU is an RX 6600 8GB if that helps

**Comment by lshqqytiger** [comment]
> Where should I put the other models I've manually downloaded, just drop it inside the usual place?

`stable-diffusion-webui-directml` folder has same files and folders without `.git` folder. So there is nothing different. Just place your models in `models\Stable-diffusion` folder.

The quality of upscaled image depends on which upscaler did you used and options, etc.

**Comment by lshqqytiger** [comment]
> I have the same issue except there's no nvidia drivers on my PC and followed all the same instructions in this thread but nothing seems to be fixing the issue.

It can be not exactly same issue. Is setup.py trying to install torch built with CUDA?

**Comment by GryArt** [comment]
> I have the same issue except there's no nvidia drivers on my PC and followed all the same instructions in this thread but nothing seems to be fixing the issue. GPU is an RX 6600 8GB if that helps

In my case, I swap out GPUs fairly often to test and after a while it gets to the point where no matter what I do there are always some traces, leftovers somewhere, running in the background, hidden deep in the services, and it's super annoying to get rid of them. 

But, if you are certain that there is no Nvidia driver leftovers in your system, I guessing but the errors you're having should be somewhat different than mine?

**Comment by JABirchall** [comment]
Im now also getting this after pullling the latest git as i hadnt updated in a few months.

```
venv "J:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 3f52b28025efbc52c2a745d34bc7ed37710c7a1c
Installing requirements
Launching Web UI with arguments:
Traceback (most recent call last):
  File "J:\stable-diffusion-webui-directml\launch.py", line 372, in <module>
    start()
  File "J:\stable-diffusion-webui-directml\launch.py", line 363, in start
    import webui
  File "J:\stable-diffusion-webui-directml\webui.py", line 37, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "J:\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "J:\stable-diffusion-webui-directml\modules\shared.py", line 13, in <module>
    import modules.interrogate
  File "J:\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "J:\stable-diffusion-webui-directml\modules\devices.py", line 4, in <module>
    import torch_directml
  File "J:\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\__init__.py", line 16, in <module>
    import torch_directml_native
ImportError: DLL load failed while importing torch_directml_native: The specified procedure could not be found.
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Try removing venv folder.

**Comment by fxr256** [comment]
I had the same issue and managed to fix it by removing the "nvidia-smi" file in C:\Windows\System32. If "nvidia-smi" is on your path then the launch.py script will decide to download the Nvidia version of torch. Sadly, "nvidia-smi" isn't removed when you uninstall all Nvidia software and hence launch.py will get incorrect results on machines where a Nvidia card was replaced with an AMD one. Maybe it makes sense to prompt the user to verify whether the auto detection was correct to make the script more robust.

**Comment by JABirchall** [comment]
> Try removing venv folder.

This worked for me.

**Comment by Joeyd348039** [comment]
I tried those solutions and no luck. I installed torch-directml but still no luck. 

I keep getting these errors:
torch-directml 0.2.0.dev230426 requires torch==2.0.0, but you have torch 2.0.1 which is incompatible.
torchvision 0.15.1 requires torch==2.0.0, but you have torch 2.0.1 which is incompatible.

Then when I downgrade to 2.0.0 I get these errors:
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.

**Comment by lshqqytiger** [comment]
Did you have NVIDIA GPU before? Its driver can remain your system.

**Comment by Joeyd348039** [comment]
> Did you have NVIDIA GPU before? Its driver can remain your system.

Yeah. Do I feel dumb, is this script only for AMD gpu's?

**Comment by lshqqytiger** [comment]
No. But I can't test on NVIDIA GPUs because I haven't any of them.
I'll check launch_util again.

**Comment by lshqqytiger** [comment]
I pushed a commit which implemented `--backend` commandline argument.
You can choose which backend will be used.
If you have a NVIDIA GPU, it selects 'cuda' automatically. You can change it to DirectML using `--backend directml`.

**Comment by Joeyd348039** [comment]
> I pushed a commit which implemented `--backend` commandline argument. You can choose which backend will be used. If you have a NVIDIA GPU, it selects 'cuda' automatically. You can change it to DirectML using `--backend directml`.

I updated, and tried with and without the argument. Still getting the Torch_DirectML error. 

If I don't use any agrs I get these errors:
fatal: No names found, cannot describe anything.
ModuleNotFoundError: No module named 'onnxruntime'

**Comment by marcuszwarg** [comment]
> Try removing venv folder.

This resolved this issue for me. 

I had an RTX 3070 gpu and have upgraded to a 7900 XTX for the Vram. I had this issue, then i used DDU (Display Driver Uninstaller) to remove the remaining stealthy Nvidia stuff from the system.

This issue persisted, even tried adding --backend directml to the web ui arguments.
Removing the Venv folder was the solution. Posted it all here so it might help a fellow SD artist. Cheers!

**Comment by lusp75** [comment]
simply add to requirements.txt in main folder, torch-directml.
Then open CMD prompt and digit webui.bat --use-directml --debug

**Comment by linzhanyu** [comment]
![2024-03-24_11-48-20](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/2173054/3d812209-fc1d-40c9-b7d3-11b8e16a7082)
Who can help me ?

**Comment by Gonzalo1987** [comment]
> ![2024-03-24_11-48-20](https://private-user-images.githubusercontent.com/2173054/316282190-3d812209-fc1d-40c9-b7d3-11b8e16a7082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NzgxOTksIm5iZiI6MTcxMTY3Nzg5OSwicGF0aCI6Ii8yMTczMDU0LzMxNjI4MjE5MC0zZDgxMjIwOS1mYzFkLTQwYzktYjdkMy0xMWI4ZTE2YTcwODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMDIwNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ4ZmU1NWZiYTM1ZDNiNjhmOTVmYTkyMzYxZmRjNDdkMTJmNjY2OWU1YTNjMzM0MWI3YjBlOTg2ZmNiMzljNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sfCErOrg-Ns7RWRyijSL-AFUOW4BMJpMPUIrSDhB9Zk) Who can help me ?

I have exactly the same problem.

**Comment by lshqqytiger** [comment]
1. Make your clone up to date.
2. Remove `venv` folder.
3. Launch webui with `--use-directml`.

**Comment by 793834982** [comment]
[> 1. Make your clone up to date.
> 2. Remove `venv` folder.
> 3. Launch webui with `--use-directml`.](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/issues/111#issuecomment-2026550360)
这个说的对，我按这么弄，成功了，成功调用了GPU进行图片渲染，以前都是用的cpu渲染的

**Comment by Checo2055** [comment]
> 1. Make your clone up to date.
> 2. Remove `venv` folder.
> 3. Launch webui with `--use-directml`.

This work for me
