### ISSUE TITLE
[Bug]: Error keeps popping up

### ISSUE THREAD

**Issue by Spas120** [lshqqytiger/stable-diffusion-webui-directml#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

there is a error that keeps saying "RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'" and idk how to fix it

### Steps to reproduce the problem

Just clicking generate

### What should have happened?

generates images without showing that error

### Commit where the problem happens

im not sure

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

CPU

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --medvram --autolaunch
```

### List of extensions

Image browser

### Console logs

```Shell
Error completing request
Arguments: ('task(44fk019k5nt5yh4)', 'Pikachu', 'low quality', [], 25, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 719, in process_images_inner
    p.setup_conds()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 1097, in setup_conds
    super().setup_conds()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 338, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.negative_prompts, self.steps * self.step_multiplier, self.cached_uc)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 329, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\prompt_parser.py", line 143, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
    return self.text_model(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 378, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    return F.layer_norm(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by Spas120** [comment]
> Add `--no-half` on commandline arguments and try again.

it became slower but it works! thank you!

**Comment by fnordKL** [comment]
adding `--no-half` works - but generation is much slower than commit before
went up from ~1.8s/it to ~15s/it

**Comment by Spas120** [comment]
> adding `--no-half` works - but generation is much slower than commit before went up from ~1.8s/it to ~15s/it

is there anyway to fix that?

**Comment by lshqqytiger** [comment]
Should be solved by https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/ab1ef3e12982c8bf63fed1485929d4565394111f

**Comment by happysad2021** [comment]
Sorry to say this, but the bug is not fixed. I am still having the issue and required --no-half, but this really slows the generation with CPU used.
