### ISSUE TITLE
[Bug]: Cannot launch on WSL due to failed installation of onnxruntime-directml

### ISSUE THREAD

**Issue by McSeaw** [lshqqytiger/stable-diffusion-webui-directml#371]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I try to launch webui.sh of commit adaea46e1c19d9a7091f89b0a7c6e66dfa732528 in my WSL environment (Ubuntu 22.04, Win 11, Python 3.10.12), it occurs an error that `pip install onnxruntime-directml` is failed. It reports that No matching distribution found for onnxruntime-directml. I try to find if onnxruntime-directml is compatible with WSL, but answers seem unsure. Is there any way to skip onnx temporarily? I have not used it once so far.

### Steps to reproduce the problem

`./webui.sh --no-gradio-queue --use-directml --opt-sub-quad-attention --lowvram --precision full --no-half --no-half-    vae --opt-split-attention-invokeai --disable-nan-check --always-batch-cond-uncond --sub-quad-q-chunk-size 512 --sub-    quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --upcast-sampling`

### What should have happened?

run the weiui.sh successfully

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

The sysinfo file is generated in commit d500e58a65d99bfaa9c7bb0da6c3eb5704fadf25, which is the latest runnable version for me.
[sysinfo-2024-02-07-17-03.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14196954/sysinfo-2024-02-07-17-03.json)

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on * user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
fatal: 没有发现名称，无法描述任何东西。
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Version: 1.7.0
Commit hash: adaea46e1c19d9a7091f89b0a7c6e66dfa732528
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
/home/*/stable-diffusion-webui-directml/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Installing onnxruntime-directml
Traceback (most recent call last):
  File "/home/*/stable-diffusion-webui-directml/launch.py", line 48, in <module>
    main()
  File "/home/*/stable-diffusion-webui-directml/launch.py", line 39, in main
    prepare_environment()
  File "/home/*/stable-diffusion-webui-directml/modules/launch_utils.py", line 628, in prepare_environment
    run_pip("install onnxruntime-directml", "onnxruntime-directml")
  File "/home/*/stable-diffusion-webui-directml/modules/launch_utils.py", line 150, in run_pip
    return run(
  File "/home/*/stable-diffusion-webui-directml/modules/launch_utils.py", line 122, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install onnxruntime-directml.
Command: "/home/*/stable-diffusion-webui-directml/venv/bin/python3" -m pip install onnxruntime-directml --prefer-binary
Error code: 1
stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by lshqqytiger** [comment]
Fixed: 4161f91465dcb9ba4b817230f607d7441bf6481b

**Comment by McSeaw** [comment]
New error occurs! I still cannot launch it in commit 4161f91465dcb9ba4b817230f607d7441bf6481b. When `import optimum.onnxruntime` it throws an exception that `ModuleNotFoundError: No module named 'optimum'`. Should I show the detail in a new issue?

**Comment by lshqqytiger** [comment]
There's a same issue exists. Remove `venv` folder and try again. If the error persists, install optimum manually.
