### ISSUE TITLE
[Bug]:  Specified module could not be found cublas64_11.dll - Fresh Install eb28651

### ISSUE THREAD

**Issue by xzenocrimzie** [lshqqytiger/stable-diffusion-webui-directml#429]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Performing a fresh install, perform fresh install process until you receive error: 
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.
Error is encountered after using "--use-directml" for the first time in the args. 

### Steps to reproduce the problem

1. Pull GIT build on commit eb28651 to dir
2. run webui-user.bat (Python 3.10.10) (note that this also happens on 3.10.6)
3. update pip to 24.0
4. add --use-directml to COMMANDLINE_ARGS
5. Encounter error `OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.`

### What should have happened?

WebUI should have built Torch and either completed installation or hit some other sort of error. 

### What browsers do you use to access the UI ?

Brave

### Sysinfo

Can't generate sysinfo file because it throws error: 
` File "C:\Games\stable-diffusion-webui-directml\modules\sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
ModuleNotFoundError: No module named 'ldm'`

lmk what other info should be in the sysinfo dump

### Console logs

```Shell
venv "C:\Games\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
*** Error running preload() for C:\Games\stable-diffusion-webui-directml\extensions-builtin\LDSR\preload.py
    Traceback (most recent call last):
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Games\stable-diffusion-webui-directml\extensions-builtin\LDSR\preload.py", line 2, in <module>
        from modules import paths
      File "C:\Games\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
        import modules.safe  # noqa: F401
      File "C:\Games\stable-diffusion-webui-directml\modules\safe.py", line 6, in <module>
        import torch
      File "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
        raise err
    OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

---
*** Error running preload() for C:\Games\stable-diffusion-webui-directml\extensions-builtin\Lora\preload.py
    Traceback (most recent call last):
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Games\stable-diffusion-webui-directml\extensions-builtin\Lora\preload.py", line 2, in <module>
        from modules import paths
      File "C:\Games\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
        import modules.safe  # noqa: F401
      File "C:\Games\stable-diffusion-webui-directml\modules\safe.py", line 6, in <module>
        import torch
      File "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
        raise err
    OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

---
*** Error running preload() for C:\Games\stable-diffusion-webui-directml\extensions-builtin\ScuNET\preload.py
    Traceback (most recent call last):
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Games\stable-diffusion-webui-directml\extensions-builtin\ScuNET\preload.py", line 2, in <module>
        from modules import paths
      File "C:\Games\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
        import modules.safe  # noqa: F401
      File "C:\Games\stable-diffusion-webui-directml\modules\safe.py", line 6, in <module>
        import torch
      File "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
        raise err
    OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

---
*** Error running preload() for C:\Games\stable-diffusion-webui-directml\extensions-builtin\SwinIR\preload.py
    Traceback (most recent call last):
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "C:\Games\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Games\stable-diffusion-webui-directml\extensions-builtin\SwinIR\preload.py", line 2, in <module>
        from modules import paths
      File "C:\Games\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
        import modules.safe  # noqa: F401
      File "C:\Games\stable-diffusion-webui-directml\modules\safe.py", line 6, in <module>
        import torch
      File "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
        raise err
    OSError: [WinError 126] The specified module could not be found. Error loading "C:\Games\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

---
Traceback (most recent call last):
  File "C:\Games\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Games\stable-diffusion-webui-directml\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "C:\Games\stable-diffusion-webui-directml\modules\launch_utils.py", line 675, in dump_sysinfo
    from modules import sysinfo
  File "C:\Games\stable-diffusion-webui-directml\modules\sysinfo.py", line 12, in <module>
    from modules import paths_internal, timer, shared, extensions, errors, devices
  File "C:\Games\stable-diffusion-webui-directml\modules\shared.py", line 6, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types, util
  File "C:\Games\stable-diffusion-webui-directml\modules\sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
ModuleNotFoundError: No module named 'ldm'
```

### Additional information

Windows 10 Version	10.0.17763 Build 17763 (Fresh Reinstall)
Processor	AMD Ryzen 7 7700X 8-Core Processor, 4500 Mhz, 8 Core(s), 16 Logical Processor(s)
Name	AMD Radeon RX 7800 XT
Driver Version	31.0.24027.1012

**Comment by lshqqytiger** [comment]
Fixed in 2d06ac3fa99721113ce085ec0675d1323b13ad00

**Comment by xzenocrimzie** [comment]
Removing `venv` did not fix the issue. However, deleting the repo and redownloading it from the most recent commit from the GIT allowed the process to complete normally. 

Thank you sir.
